version: '3.3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: app-client
    volumes:
      - ./client/src:/usr/app/src
    ports:
      - 6969:6969
      - 1234:1234
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=9696
      - CHOKIDAR_USEPOLLING=true
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: app-server
    volumes:
      - ./server/src:/usr/app/src
    ports:
      - 9696:9696
    links:
      - db
    depends_on:
      - db
    environment:
      - CLIENT_HOST=client
      - CLIENT_PORT=6969
      - DATABASE_CONNECTION_STRING=postgresql://postgres:password@db:5432/management-app
  db:
    image: postgres:9.6
    container_name: app-db
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - 25432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=management-app
volumes:
  db-data:
    driver: local
